version: '2.1'

jobs:
  ########################## UNIT TESTS ##########################
  unit-tests:
    working_directory: ~/go/src/github.com/jose-camilo/simplecalc
    docker:
      - image: cimg/go:1.18
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -cover -v $(go list ./... | circleci tests split --split-by=timings) |& tee /tmp/test.out

  ########################## ARM64 BUILD ##########################
  build-arm64:
    working_directory: ~/go/src/github.com/jose-camilo/simplecalc
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Update Dependencies
          command: go mod download
      - run:
          name: Build
          command: |
            GOOS=linux GOARCH=arm64 go build -o simplecalc .
      - store_artifacts:
          name: Push Image
          path: ~/go/src/github.com/jose-camilo/simplecalc/simplecalc
          destination: simplecalc-arm64

  ########################## 386 BUILD ##########################
  build-386:
    working_directory: ~/go/src/github.com/jose-camilo/simplecalc
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Update Dependencies
          command: go mod download
      - run:
          name: Build
          command: |
            GOOS=linux GOARCH=386 go build -o simplecalc .
      - store_artifacts:
          name: Push Image
          path: ~/go/src/github.com/jose-camilo/simplecalc/simplecalc
          destination: simplecalc-386

  ########################## AMD64 BUILD ##########################
  build-amd64:
    working_directory: ~/go/src/github.com/jose-camilo/simplecalc
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Update Dependencies
          command: go mod download
      - run:
          name: Build
          command: |
            GOOS=linux GOARCH=amd64 go build -o simplecalc .
      - store_artifacts:
          name: Push Image
          path: ~/go/src/github.com/jose-camilo/simplecalc/simplecalc
          destination: simplecalc-amd64

workflows:
  main:
    jobs:
      - unit-tests:
          filters:
            branches:
              only: main
      - build-arm64:
          requires:
            - unit-tests
      - build-amd64:
          requires:
            - unit-tests
      - build-386:
          requires:
            - unit-tests
      - promote:
          type: approval
          requires:
            - build-arm64
            - build-amd64
            - build-386
      - dummy-release:
          type: approval
          requires:
            - promote






