version: '2.1'

orbs:
  go: circleci/go@1.7.0  # Version number pertains to CircleCI Orb version, not Go version

jobs:
  unit-tests:
    executor:
      name: go/default
      tag: '1.18'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          race: true
          verbose: true
workflows:
  main:
    jobs:
      - unit-tests